<a href="https://colab.research.google.com/github/MariiaKalinina/Skoltech/blob/main/Untitled46.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

def create_dataframe_with_values():
    result_df = pd.DataFrame()

    for i in range(10):  # Iterate 10 times to add 10 columns
        new_col_name = f'Column_{i+1}'
        new_col_values = np.random.randint(1, 100, size=10)  # Generate 10 random values for the column
        result_df[new_col_name] = new_col_values

    return result_df

# Call the function to create the DataFrame with 10 columns, each containing 10 random values
result_dataframe = create_dataframe_with_values()

print(result_dataframe)

   Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0        25        56        38        92        28        90        18
1        72        93        61        84        37        16        21
2        65        49        64        91        94        29        57
3        65        23        76        68        13        81        32
4        11        57         3        34        66        93        40
5        71        80        29        83        93        97        58
6        47         6        48        86        34        12        34
7        41        43        27        79        38        98        42
8        83        30        90        98        72        65         8
9        94         7        47        61        32        45        59

   Column_8  Column_9  Column_10
0        38        54         78
1        32        99         75
2        14        66         13
3        22        38         32
4        22        88          7
5        42        45         88
6        67        83         13
7        69        87          3
8         7        35         39
9         6        24         83

In [43]:
import pandas as pd
import numpy as np
from math import *
from scipy.special import lambertw

In [309]:
# import pandas as pd

df_constast = pd.read_csv('/content/Constants.csv', delimiter=';', header=0)
# df_constast.columns = ['name_lithology_type', 'porosity', 'exp_decay', 'grain_density', 'tc_matrix', 'radiogenic_heat_production', 'Ki_framework']

df_well = pd.read_csv('/content/Well_parametrs.csv', delimiter=';', header=0)

In [312]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0.00,0.00,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5.40,5.40,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [311]:
df_well[['Depth top, m', 'Depth bottom, m']] = df_well[['Depth top, m', 'Depth bottom, m']].apply(lambda x: x / 1000)

In [294]:
df_constast

,Lithology_type,Porosity,"Exp_decay, km-1",Grain density,TC matrix,Radiogenic Heat Production,Ki_framework
0,Shales,0.63,0.51,2720,2.0,1.700000e-06,2.0
1,Sandstones,0.49,0.27,2650,5.5,1.200000e-06,5.5
2,Chalk,0.70,0.71,2710,3.3,4.000000e-07,3.3
3,Limestones,0.40,0.60,2710,3.3,5.000000e-07,3.3
4,Dolomite,0.30,0.60,2870,5.3,4.000000e-07,5.3
5,Anhydrite,0.05,0.20,2960,6.3,1.000000e-07,6.3
6,Quartzite,0.20,0.30,2650,7.7,5.000000e-07,7.7
7,Fundament,0.00,0.00,2800,3.0,2.800000e-06,3.0

In [270]:
df_constast.columns

Index(['Lithology_type', 'Porosity', 'Exp_decay', 'Grain density', 'TC matrix',
       'Radiogenic Heat Production', 'Ki_framework'],
      dtype='object')

In [271]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0,0,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0,200,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,200,450,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,450,1200,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1200,2500,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2500,3400,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3400,3600,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3600,4000,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4000,4250,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4250,5000,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5000,5400,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5400,5400,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [272]:
df_well.columns

Index(['Well', 'Event_name', 'Event_type', 'Lithology_type', 'Age (Ma)',
       'Depth top, m', 'Depth bottom, m', 'Thickness, m',
       'D Thickness (erosion), m', 'Paleobathymetry, Ma', 'Sea level, m',
       'Sublayers', 'PSE', 'Kinetic', 'TOC initial, %', 'HI initial, %'],
      dtype='object')

In [273]:
# Create a sample DataFrame
df = pd.DataFrame({'col_0': list('ABCDEFGHIJ'), 'col_1': range(9, -1, -1)})

# Iterate over the DataFrame rows using iterrows()
for row_index, row in enumerate(df.iterrows()):
    index, data = row
    # print(index, row)
    if row_index == 3:  # Select row at index 3
        selected_row = data
        print(f"Selected Row at index {row_index}:\n{selected_row}")

Selected Row at index 3:
col_0    D
col_1    6
Name: 3, dtype: object

In [274]:
layers_quantity = len(df_well[1:df_well.shape[0]-1]) #amount of layers for calculation
layers_quantity

10

In [275]:
work_layers = df_well[1:df_well.shape[0]-1]

In [276]:
work_layers

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
1,Test_well,Layer 10,Erosion,Shales,0,0,200,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,200,450,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,450,1200,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1200,2500,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2500,3400,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3400,3600,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3600,4000,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4000,4250,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4250,5000,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5000,5400,400,NaN,0,0,1,NaN,NaN,NaN,NaN

In [277]:
# filtered_df = df_well[df_well['Event_name'] != 'Erosion']

In [278]:
def decomp_func(y1, y2, y1_d, phi, c):  # возвращает фун-ию одной переменной, для которой затем подбирается параметр y2_d

    y2_d = (np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) - \
            np.exp(-np.log(e) * y1 * c) * phi * np.log(e) + \
            np.exp(-np.log(e) * y2 * c) * phi * np.log(e) - \
            np.log(e) * y1 * c + np.log(e) * y1_d * c + np.log(e) * y2 * c + \
            lambertw(-np.log(e) * phi * np.exp(-np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) +\
                                               np.exp(-np.log(e) * y1 * c) * phi * np.log(e) - \
                                               np.exp(-np.log(e) * y2 * c) * phi * np.log(e) + \
                                               np.log(e) * y1 * c - \
                                               np.log(e) * y1_d * c - np.log(e) * y2 * c))) / c / np.log(e)
    return y2_d.real

In [116]:
df_constast.columns

Index(['Lithology_type', 'Porosity', 'Exp_decay', 'Grain density', 'TC matrix',
       'Radiogenic Heat Production', 'Ki_framework'],
      dtype='object')

In [328]:
calculation_order = []
# age = list(df_well['Age (Ma)'][1:])

age = list(df_well['Age (Ma)'][9:])
thickness_dict = {}

for i, a in enumerate(age, start=8):
    print('Age', i, a)

    work_layers_copy = work_layers.copy()
    rows_to_delete = []
    thinkness_sum = []

    # print(work_layers_copy['Event_name'][i::])

    for row_index, row in enumerate(work_layers_copy[i::].itertuples(), start=i):

      # print(row_index)

      lithology = work_layers_copy.at[row.Index, 'Lithology_type']
      layers_name = work_layers_copy.at[row.Index, 'Event_name']

      # y2_d = 0


      if row_index == i:
        print('first')
        y1_d = 0


      else:
        # y1_d = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[-1]
        y1_d = y2_d



      phi0 = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Porosity'].iloc[0]
      c = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Exp_decay, km-1'].iloc[0]
      y1 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[0]
      y2 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth bottom, m'].iloc[0]


      y2_d = decomp_func(y1, y2, y1_d, phi0, c)


      thicknesses = np.round(y2_d - y1_d, 3) #A58.3
      thinkness_sum.append(thicknesses)



      print(row_index, lithology, layers_name, y1, y2, thicknesses, y1_d, y2_d, phi0, c)
    print(sum(thinkness_sum))
    print('\n')


      # print(work_layers_copy['Event_name'])

      # rows_to_delete.append(row.Index - i)
      # print(rows_to_delete)




    # Delete the rows above the current rows in work_layers_copy, excluding the first row
    # work_layers_copy.drop(rows_to_delete[1:], inplace=True)

    # print(work_layers_copy['Event_name'])

Age 8 210
first
8 Anhydrite Layer 2 4.25 5.0 0.771 0 0.7708338613738266 0.05 0.2
9 Quartzite Layer 1 5.0 5.4 0.45 0.7708338613738266 1.2208184835587517 0.2 0.3
1.221


Age 9 245
first
9 Quartzite Layer 1 5.0 5.4 0.471 0 0.4710320563997708 0.2 0.3
0.471


Age 10 260
0

In [147]:
for i in age:
    print(i)

    # Create a copy of work_layers to avoid modifying the original DataFrame
    work_layers_copy = work_layers.copy()

    for row_index, row in enumerate(work_layers_copy.itertuples()):
        if row_index > 0:  # Skip the first row
            lithology = work_layers_copy.at[row.Index, 'Lithology_type']
            layers_name = work_layers_copy.at[row.Index, 'Event_name']

            phi0 = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Porosity'].iloc[0]
            c = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Exp_decay'].iloc[0]
            y1 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[0]
            y2 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth bottom, m'].iloc[0]

            # Perform operations using the selected data

            # Delete the row above the current row in work_layers_copy
            work_layers_copy.drop(work_layers_copy.index[row_index - 1], inplace=True)

0

KeyError: 5

In [ ]:
def func_general_decomp_equation_mine(y1, y2, y1_d, phi, c):  # возвращает фун-ию одной переменной, для которой затем подбирается параметр y2_d

  y2_d = (np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) - \
      np.exp(-np.log(e) * y1 * c) * phi * np.log(e) + \
      np.exp(-np.log(e) * y2 * c) * phi * np.log(e) - \
      np.log(e) * y1 * c + np.log(e) * y1_d * c + np.log(e) * y2 * c + \
      lambertw(-np.log(e) * phi * np.exp(-np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) +\
                          np.exp(-np.log(e) * y1 * c) * phi * np.log(e) - \
                          np.exp(-np.log(e) * y2 * c) * phi * np.log(e) + \
                          np.log(e) * y1 * c - \
                          np.log(e) * y1_d * c - np.log(e) * y2 * c))) / c / np.log(e)
  return y2_d

In [ ]:
 result_df = pd.DataFrame()

In [ ]:
if df_well['name_lithology_type'] != 'NaN':

				y1_p = df_well["top"]
        print(y1_p)
				y2_p = df_well["bottom"]

        mask = df_well["name_lithology_type"].eq('chair')
        phi0 = df_constast["porosity"][mask].values[0]

        phi0 = df_constast["porosity"]

				phi0 = lithology_dict[lithology]['porosity']
				sedimentation_depth = well_decompaction_data[well_name][layer]['Paleobathymetry']
				c = lithology_dict[well_decompaction_data[well_name][layer]['name_lithology_type']]['exp_decay']
				a = lithology_dict[well_decompaction_data[well_name][layer]['name_lithology_type']]['radiogenic_heat_production']
				#phi0 = calculate_porosity(phi0, c, sedimentation_depth)
				h = y2_p-y1_p

				age = parameters['Age']

				wd = well_decompaction_data[well_name][layer]['Paleobathymetry']
				sl = well_decompaction_data[well_name][layer]['delta_sl']

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [ ]:
values = ["Name", "Age", "City", "State"]
data = []

for i in range(5):
  row = {
"Name": "Person " + str(i),
"Age": 30 + i,
"City": "City " + str(i % 2),
"State": "State " + str(i // 2)
}
  data.append(row)
  df = pd.DataFrame(data, columns=values)
print(df)

       Name  Age    City    State
0  Person 0   30  City 0  State 0
1  Person 1   31  City 1  State 0
2  Person 2   32  City 0  State 1
3  Person 3   33  City 1  State 1
4  Person 4   34  City 0  State 2

In [ ]:
RoWater, RoMantle = 3300, 1000

In [ ]:
po = ()

In [ ]:
2.2+0.1

In [ ]:
RoWater, RoMantle = 3300, 1000

In [ ]:
po = (RoWater/ (RoMantle-RoWater))

In [ ]:
po

-1.434782608695652

In [ ]:
w = -20
d = 10

In [ ]:
s = 0.470*1000

In [ ]:
s_new = s - d*po + (w-d)

In [ ]:
s_new/1000

0.4543478260869565